namespace server.Models.Domain.Enums;

public enum AssetStatus
{
    PENDING_IMPORT,
    IMPORTED,
    IMPORT_ERROR,
    PENDING_PROCESSING,
    PROCESSING,
    PROCESSING_ERROR,
    READY_FOR_ANNOTATION,
    ANNOTATION_IN_PROGRESS,
    ANNOTATED,
    PENDING_REVIEW,
    REVIEW_IN_PROGRESS,
    REVIEW_ACCEPTED,
    REVIEW_REJECTED,
    EXPORTED,
    ARCHIVED
}
