namespace server.Models.Domain.Enums;

public enum TaskEventType
{
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    STAGE_CHANGED,
    STATUS_CHANGED,
    COMMENT_ADDED,
    ANNOTATION_CREATED,
    ANNOTATION_UPDATED,
    ANNOTATION_DELETED,
    REVIEW_SUBMITTED,
    ISSUE_RAISED,
    PRIORITY_CHANGED,
    DUE_DATE_CHANGED,
}
